### ISSUE TITLE
OSError: no matching service

### ISSUE THREAD

**Issue by MonsieurSingh** [sdushantha/svart#1]
Traceback (most recent call last):
  File "/usr/local/bin/svart", line 33, in <module>
    sys.exit(load_entry_point('svart==1.0.0', 'console_scripts', 'svart')())
  File "/usr/local/bin/svart", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.9/site-packages/svart-1.0.0-py3.9.egg/svart/__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.9/site-packages/svart-1.0.0-py3.9.egg/svart/svart.py", line 10, in <module>
OSError: no matching service

**Comment by sdushantha** [comment]
@Teghjyot Could you please provide the command you executed which gave this command? I think this is an issue with your environment and not a bug in `svart`.

**Comment by j450h1** [comment]
```
Jass-MacBook-Air:~ $ svart
```
Traceback (most recent call last):
  File "/Users/jas/.local/bin/svart", line 5, in <module>
    from svart.svart import main
  File "/Users/jas/.local/lib/python3.7/site-packages/svart/__init__.py", line 1, in <module>
    from .svart import main
  File "/Users/jas/.local/lib/python3.7/site-packages/svart/svart.py", line 10, in <module>
    import als
OSError: no matching service       

Same thing here. On Big Sur, with MacBook air 2020 (non M1)

**Comment by david-roquis** [comment]
Same issue here on a MBP 15' 2017 with Big Sur 11.2.3

svart ambient or svart -h returns 

Traceback (most recent call last):
  File "/Users/david/.local/bin/svart", line 5, in <module>
    from svart.svart import main
  File "/Users/david/.local/lib/python3.8/site-packages/svart/__init__.py", line 1, in <module>
    from .svart import main
  File "/Users/david/.local/lib/python3.8/site-packages/svart/svart.py", line 10, in <module>
    import als
OSError: no matching service

**Comment by sdushantha** [comment]
It looks like it is an issue with `als`. Could you guys try running the code below?
```python
import als
print(als.getSensorReadings())
```

The code above works for me on MacBook Air (13-inch, Early 2015)

**Comment by david-roquis** [comment]
Indeed it seems to be an als issue

❯ python
Python 3.8.6 | packaged by conda-forge | (default, Nov 27 2020, 19:17:44)
[Clang 11.0.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import als
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: no matching service

als seems to be properly installed on my system though 
python3 -m pip install als
Requirement already satisfied: als in ./miniconda3/lib/python3.8/site-packages (0.0.2)

**Comment by sdushantha** [comment]
I found the email of the author of `alsmodule-pkg` in the `setup.py` file. I can email them and ask if they are able to help us out with this issue because the actual module is written in C, which I know nothing about. Not sure if they have GitHub, otherwise I'd ping them from here.

**Comment by MonsieurSingh** [comment]
> @Teghjyot Could you please provide the command you executed which gave this command? I think this is an issue with your environment and not a bug in `svart`.

Any 'svart' command returns this error dialogue whereas, other services using python don't.

**Comment by SaalimQamar** [comment]
Hi everyone, I am trying to figure this error but had no success yet. Could I please get some help with the als module? When I run `svart -d`, I get the following debug report: 
```
svart is now running...
System mode at start: light
Traceback (most recent call last):
  File "/usr/local/bin/svart", line 33, in <module>
    sys.exit(load_entry_point('svart==1.0.0', 'console_scripts', 'svart')())
  File "/usr/local/lib/python3.9/site-packages/svart-1.0.0-py3.9.egg/svart/svart.py", line 107, in main
AttributeError: module 'als' has no attribute 'getSensorReadings'
```
als is installed `als in /usr/local/lib/python3.9/site-packages (0.0.2)`

When I run `svart ambient`, I get the following:
```
Traceback (most recent call last):
  File "/usr/local/bin/svart", line 33, in <module>
    sys.exit(load_entry_point('svart==1.0.0', 'console_scripts', 'svart')())
  File "/usr/local/lib/python3.9/site-packages/svart-1.0.0-py3.9.egg/svart/svart.py", line 88, in main
ValueError: invalid literal for int() with base 10: 'ambient'
```
I have python 3.9 installed through homebrew. 
Thanks for your help!
